### ISSUE TITLE
Mobile app function call not working in ERPNext v13

### ISSUE THREAD

**Issue by buff0k** [frappe/mobile#47]
Opening this here as it appears to be an issue with the API call in the mobile app:
https://github.com/frappe/erpnext/issues/25537
https://github.com/frappe/erpnext/issues/25213

Initially manifested as 404 error in the app, progressed to 417 with later builds of ERPNext.

**Comment by sumitbhanushali** [comment]
@buff0k 
ERPNext Mobile App [cordova-wrapper](https://github.com/frappe/cordova-wrapper) does not support V13, you can access ERPNext from Mobile Browser though since it'll give same experience.

This Project (frappe/mobile) is native mobile app implementation of Frappe Framework built from scratch and is different from one you have mentioned

**Comment by jlhollowell** [comment]
Just curious if there is any activity toward fixing the app? The browser interface does not implement bar code / QR code scanning into fields. I think the app was supposed to have this functionality but am unable to verify as it fails with 417 error.

**Comment by HDPortes** [comment]
@jlhollowell Hi! 

In the web app, try creating a sales invoice.

That's where the scan should come. If you open it from a mobile browser

**Comment by jlhollowell** [comment]
66portes,

Thanks for your comment. I gave that a try but I don't see any fields in the sales invoice that allow me to access the camera on my phone to be used as a QR code reader. I need to be able to read scans when entering patients in the Healthcare app though so I guess I will need to have this functionality developed either via the web app or via the standalone app.

Regards

Jason
